Feature/converter
arx-8/dbflute-schema-ex pull request #1
Opened 2019-03-17 03:40 UTC by HYKTSNG

SQLの組み立て処理の実装

2019-03-17 14:18 UTC, arx-8 requested changes

2019-03-17 14:18 UTC, arx-8 commented on src/util/SqlUtils.ts
> +  let s = 0
これ、自分でfor文を回すindexとして「s」を定義するのではなく、言語標準のindexを使ってみ。

https://github.com/arx-8/dbflute-schema-ex/pull/1/files#diff-6a82c5a9be264c57a499eb7fdeb1e41bR10
> for (let index = 0;
の「index」のことね。

この「index」は、まさに「s」と同じことをやりたいためにある変数なので、自分で「s」を作る必要がない。
言語標準のを使った方がコードが短くなるし、バグも少なくなるし、良い。

2019-03-17 14:20 UTC, arx-8 requested changes

2019-03-17 14:20 UTC, arx-8 commented on src/util/SqlUtils.ts
> +  // TODO
ここ、できたら実装してみて

`npm test` を全てpassできたら完成

2019-03-21 14:18 UTC, HYKTSNG commented on src/util/SqlUtils.ts
> +  let s = 0
対応した

2019-03-21 14:18 UTC, HYKTSNG commented on src/util/SqlUtils.ts
> +  // TODO
対応した

2019-03-21 14:20 UTC, arx-8 approved these changes

2019-03-21 14:21 UTC, merged